/******************************************************************************************* 
* NAME:2_Figures.do
* Date: 2025/7/10
* CREATED by ZHAN Yuyang
* NOTES:
  This document uses the datasets generated by `0_Data_Preparation.do`—namely `$dir/data/firm_level_outcomes.dta` and `$dir/data/firm_to_firm_level_outcomes.dta`—to perform regression analysis.
  The regression results are stored in:
- "$dir/results/figures/monthly_treatment_effects.pdf"

Directory：
- PRELIMINARIES
- 1. Firm-level regressions (Pre-Post Analysis)
- 2. Firm-to-firm level regressions (Pre-Post Analysis)
*******************************************************************************************/


*****************
/*PRELIMINARIES*/
*****************
clear all
set maxvar 15000
set matsize 10000

*If you want to run this dofile separately, rather than through master.do, fill in your path here.

*    global dir "E:\研究\工作研究\ct2\data task"  


*set seed
set seed 123456789


*************************************************
/*1. Firm-level regressions (Pre-Post Analysis)*/
*************************************************
use "$dir/data/firm_level_outcomes.dta", clear

* Set up
* Generate monthly treatment indicators
forval m = -6(1)12 {
    local mvar = `m'
    if `m' < 0 {
        local mvar = abs(`m')
        gen treat_month_neg`mvar' = (months_to_fair == `m') * treat
    }
    else {
        gen treat_month_`mvar' = (months_to_fair == `m') * treat
    }
}


*Plotting the results for suppliers
local firm_outcomes "outcome_value n_partners n_products new_partners" //Define outcome variables: Whether there is a sale (or purchase). Number of transactions. Total sales amount.

* Create matrices to store results
matrix supplier_coef = J(19, 4, .)
matrix supplier_se = J(19, 4, .)

local col = 1
foreach outcome in `firm_outcomes' {
    
    * Run regression with monthly treatment effects (excluding -1 as base period)
    reghdfe `outcome' treat_month_neg6 treat_month_neg5 treat_month_neg4 treat_month_neg3 treat_month_neg2 treat_month_0 treat_month_1 treat_month_2 treat_month_3 treat_month_4 treat_month_5 treat_month_6 treat_month_7 treat_month_8 treat_month_9 treat_month_10 treat_month_11 treat_month_12 if type == "supplier", ///
        absorb(firm_id months_to_fair strata_id#c.months_to_fair) ///
        cluster(firm_id)
    
    * Store coefficients and standard errors
    local row = 1
    * Months -6 to -2
    foreach var in treat_month_neg6 treat_month_neg5 treat_month_neg4 treat_month_neg3 treat_month_neg2 {
        matrix supplier_coef[`row', `col'] = _b[`var']
        matrix supplier_se[`row', `col'] = _se[`var']
        local ++row
    }
    * Month -1 (base period): coefficient = 0, se = 0
    matrix supplier_coef[`row', `col'] = 0
    matrix supplier_se[`row', `col'] = 0
    local ++row
    * Months 0 to 12
    foreach var in treat_month_0 treat_month_1 treat_month_2 treat_month_3 treat_month_4 treat_month_5 treat_month_6 treat_month_7 treat_month_8 treat_month_9 treat_month_10 treat_month_11 treat_month_12 {
        matrix supplier_coef[`row', `col'] = _b[`var']
        matrix supplier_se[`row', `col'] = _se[`var']
        local ++row
    }
    local ++col
}

* Convert matrices to dataset for plotting
preserve
clear
set obs 19
gen month = _n - 7  // -6 to 12
gen zero = 0  // Create zero reference line
svmat supplier_coef, names(coef_)
svmat supplier_se, names(se_)

* Generate confidence intervals (month -1 has zero coefficient and SE)
forval i = 1/4 {
    gen ci_upper_`i' = coef_`i' + 1.96 * se_`i'
    gen ci_lower_`i' = coef_`i' - 1.96 * se_`i'
}

* Create plots
local titles `" "Total Sales and Purchases" "Total Buyers and Suppliers" "New Buyers and Suppliers" "Products Purchased and Sold" "'
local filenames "total_sales_purchases total_buyers_suppliers new_buyers_suppliers products_purchased_sold"

tokenize `filenames'
forval i = 1/4 {
    local title : word `i' of `titles'
    
    twoway (rarea ci_upper_`i' ci_lower_`i' month, color(gs14) lwidth(none)) ///
           (line coef_`i' month, lcolor(navy) lwidth(medium)) ///
           (scatter coef_`i' month, mcolor(navy) msymbol(circle) msize(small)) ///
           (line zero month, lcolor(black) lpattern(dash)), ///
        xline(0, lcolor(red) lpattern(dash)) ///
        xlabel(-6(3)12, labsize(small)) ///
        ylabel(, labsize(small) format(%9.3f)) ///
        xtitle("Months Relative to Fair", size(small)) ///
        ytitle("Treatment Effect", size(small)) ///
        title(`title', size(medsmall)) ///
        legend(off) ///
        graphregion(color(white)) plotregion(color(white)) ///
        name(supplier_`i', replace)
}

// Combine firm-level plots
graph combine supplier_1 supplier_2 supplier_3 supplier_4, ///
    rows(2) cols(2) ///
    title("Monthly Treatment Effects: Firm-Level Outcomes (Suppliers)", size(medium)) ///
    graphregion(color(white)) ///
    name(supplier_combined, replace)

* graph export "firm_level_monthly.pdf", replace
restore


*Plotting the results for buyers
local firm_outcomes "outcome_value n_partners n_products new_partners" 

* Create matrices to store results
matrix buyer_coef = J(19, 4, .)
matrix buyer_se = J(19, 4, .)

local col = 1
foreach outcome in `firm_outcomes' {
    
    * Run regression with monthly treatment effects (excluding -1 as base period)
    reghdfe `outcome' treat_month_neg6 treat_month_neg5 treat_month_neg4 treat_month_neg3 treat_month_neg2 treat_month_0 treat_month_1 treat_month_2 treat_month_3 treat_month_4 treat_month_5 treat_month_6 treat_month_7 treat_month_8 treat_month_9 treat_month_10 treat_month_11 treat_month_12 if type == "buyer", ///
        absorb(firm_id months_to_fair strata_id#c.months_to_fair) ///
        cluster(firm_id)
    
    * Store coefficients and standard errors
    local row = 1
    * Months -6 to -2
    foreach var in treat_month_neg6 treat_month_neg5 treat_month_neg4 treat_month_neg3 treat_month_neg2 {
        matrix buyer_coef[`row', `col'] = _b[`var']
        matrix buyer_se[`row', `col'] = _se[`var']
        local ++row
    }
    * Month -1 (base period): coefficient = 0, se = 0
    matrix buyer_coef[`row', `col'] = 0
    matrix buyer_se[`row', `col'] = 0
    local ++row
    * Months 0 to 12
    foreach var in treat_month_0 treat_month_1 treat_month_2 treat_month_3 treat_month_4 treat_month_5 treat_month_6 treat_month_7 treat_month_8 treat_month_9 treat_month_10 treat_month_11 treat_month_12 {
        matrix buyer_coef[`row', `col'] = _b[`var']
        matrix buyer_se[`row', `col'] = _se[`var']
        local ++row
    }
    local ++col
}

* Convert matrices to dataset for plotting
preserve
clear
set obs 19
gen month = _n - 7  // -6 to 12
gen zero = 0  // Create zero reference line
svmat buyer_coef, names(coef_)
svmat buyer_se, names(se_)

* Generate confidence intervals (month -1 has zero coefficient and SE)
forval i = 1/4 {
    gen ci_upper_`i' = coef_`i' + 1.96 * se_`i'
    gen ci_lower_`i' = coef_`i' - 1.96 * se_`i'
}

* Create plots
local titles `" "Total Sales and Purchases" "Total Buyers and Suppliers" "New Buyers and Suppliers" "Products Purchased and Sold" "'
local filenames "total_sales_purchases total_buyers_suppliers new_buyers_suppliers products_purchased_sold"

tokenize `filenames'
forval i = 1/4 {
    local title : word `i' of `titles'
    
    twoway (rarea ci_upper_`i' ci_lower_`i' month, color(gs14) lwidth(none)) ///
           (line coef_`i' month, lcolor(navy) lwidth(medium)) ///
           (scatter coef_`i' month, mcolor(navy) msymbol(circle) msize(small)) ///
           (line zero month, lcolor(black) lpattern(dash)), ///
        xline(0, lcolor(red) lpattern(dash)) ///
        xlabel(-6(3)12, labsize(small)) ///
        ylabel(, labsize(small) format(%9.3f)) ///
        xtitle("Months Relative to Fair", size(small)) ///
        ytitle("Treatment Effect", size(small)) ///
        title(`title', size(medsmall)) ///
        legend(off) ///
        graphregion(color(white)) plotregion(color(white)) ///
        name(buyer_`i', replace)
}

// Combine firm-level plots
graph combine buyer_1 buyer_2 buyer_3 buyer_4, ///
    rows(2) cols(2) ///
    title("Monthly Treatment Effects: Firm-Level Outcomes (Buyers)", size(medium)) ///
    graphregion(color(white)) ///
    name(buyer_combined, replace)

* graph export "firm_level_monthly.pdf", replace
restore


*********************************************************
/*2. Firm-to-firm level regressions (Pre-Post Analysis)*/
*********************************************************
* Load firm-to-firm data
use "$dir/data/firm_to_firm_level_outcomes.dta", clear

* Generate monthly treatment indicators
forval m = -6(1)12 {
    local mvar = `m'
    if `m' < 0 {
        local mvar = abs(`m')
        gen treat_month_neg`mvar' = (months_to_fair == `m') * treat
    }
    else {
        gen treat_month_`mvar' = (months_to_fair == `m') * treat
    }
}

* Define firm-to-firm outcomes
local pair_outcomes "has_sale n_transactions n_products"

* Create matrices to store results
matrix pair_coef = J(19, 3, .)
matrix pair_se = J(19, 3, .)

local col = 1
foreach outcome in `pair_outcomes' {
    
    * Run regression with pair fixed effects (excluding -1 as base period)
    reghdfe `outcome' treat_month_neg6 treat_month_neg5 treat_month_neg4 treat_month_neg3 treat_month_neg2 treat_month_0 treat_month_1 treat_month_2 treat_month_3 treat_month_4 treat_month_5 treat_month_6 treat_month_7 treat_month_8 treat_month_9 treat_month_10 treat_month_11 treat_month_12, ///
        absorb(pair_id months_to_fair strata_id#c.months_to_fair) ///
        cluster(seller)
    
    * Store coefficients and standard errors
    local row = 1
    * Months -6 to -2
    foreach var in treat_month_neg6 treat_month_neg5 treat_month_neg4 treat_month_neg3 treat_month_neg2 {
        matrix pair_coef[`row', `col'] = _b[`var']
        matrix pair_se[`row', `col'] = _se[`var']
        local ++row
    }
    * Month -1 (base period): coefficient = 0, se = 0
    matrix pair_coef[`row', `col'] = 0
    matrix pair_se[`row', `col'] = 0
    local ++row
    * Months 0 to 12
    foreach var in treat_month_0 treat_month_1 treat_month_2 treat_month_3 treat_month_4 treat_month_5 treat_month_6 treat_month_7 treat_month_8 treat_month_9 treat_month_10 treat_month_11 treat_month_12 {
        matrix pair_coef[`row', `col'] = _b[`var']
        matrix pair_se[`row', `col'] = _se[`var']
        local ++row
    }
    local ++col
}

* Convert matrices to dataset for plotting
preserve
clear
set obs 19
gen month = _n - 7  // -6 to 12
gen zero = 0  // Create zero reference line
svmat pair_coef, names(coef_)
svmat pair_se, names(se_)

* Generate confidence intervals (month -1 has zero coefficient and SE)
forval i = 1/3 {
    gen ci_upper_`i' = coef_`i' + 1.96 * se_`i'
    gen ci_lower_`i' = coef_`i' - 1.96 * se_`i'
}

* Create plots
local titles `" "Sale Indicator" "Number of Transactions" "Total Sales Amount" "'
local filenames "sale_indicator n_transactions total_sales_amount"

tokenize `filenames'
forval i = 1/3 {
    local title : word `i' of `titles'
    
    twoway (rarea ci_upper_`i' ci_lower_`i' month, color(gs14) lwidth(none)) ///
           (line coef_`i' month, lcolor(navy) lwidth(medium)) ///
           (scatter coef_`i' month, mcolor(navy) msymbol(circle) msize(small)) ///
           (line zero month, lcolor(black) lpattern(dash)), ///
        xline(0, lcolor(red) lpattern(dash)) ///
        xlabel(-6(3)12, labsize(small)) ///
        ylabel(, labsize(small) format(%9.3f)) ///
        xtitle("Months Relative to Fair", size(small)) ///
        ytitle("Treatment Effect", size(small)) ///
        title(`title', size(medsmall)) ///
        legend(off) ///
        graphregion(color(white)) plotregion(color(white)) ///
        name(pair_`i', replace)
}

* Combine firm-to-firm plots
graph combine pair_1 pair_2 pair_3, ///
    cols(2) ///
    title("Monthly Treatment Effects: Firm-to-Firm Outcomes", size(medium)) ///
    graphregion(color(white)) ///
    name(pair_combined, replace) ///
	xsize(16.6) ysize(22)

* graph export "firm_to_firm_monthly.pdf", replace
restore


* Create combined plot with all outcomes
graph combine supplier_combined buyer_combined pair_combined, ///
    rows(3) ///
    title("Monthly Treatment Effects: All Outcomes", size(medium)) ///
    graphregion(color(white)) ///
    name(all_combined, replace) ///
	xsize(16.8) ysize(44)

graph export "$dir/results/figures/monthly_treatment_effects.pdf", replace

di "Analysis complete."
